language: minimal
branches:
  only:
    - master
before_install:
  - sudo apt-get install luarocks
  - sudo luarocks install busted
  - sudo luarocks install luacov-coveralls
script: busted -c tests
after_success: luacov-coveralls
notifications:
  email: false
